name: cosmos_sdk_proto
description: A dart library for Cosmos SDK protobuf files.
version: 0.46.16
repository: https://github.com/AufWallet/cosmos-sdk-proto

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  protobuf: ^3.1.0
  grpc: ^4.0.1
  fixnum: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
